### ISSUE TITLE
Panic: entered unreachable code: importing

### ISSUE THREAD

**Issue by muni-corn** [harrisonthorne/silverfox#3]
When importing a csv file:

```
thread 'main' panicked at 'internal error: entered unreachable code', src/entry.rs:248:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by muni-corn** [comment]
This issue was unable to be reproduced with a backtrace

**Comment by muni-corn** [comment]
I was able to finally reproduce this backtrace. Seems to happen when rules don't contain any "amount" rules

```
thread 'main' panicked at 'internal error: entered unreachable code', src/entry.rs:248:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: mvelopes::entry::Entry::get_blank_amount
  13: mvelopes::account::Account::process_entry
  14: mvelopes::ledger::Ledger::add_entry
  15: mvelopes::ledger::Ledger::append_entry
  16: mvelopes::ledger::Ledger::import_csv
  17: mvelopes::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  22: std::panicking::try
             at src/libstd/panicking.rs:281
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by muni-corn** [comment]
If this problem occurs, an erratic entry is imported anyways: #4
